### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by pythonbeginner14** [QAQ0428/WordleGame#1]
1.必须要rich库，我认为如果只需要彩色地输出用控制字符\033[38;2;{red};{green};{blue}m就行了，里面写rgb值，之后\033[0m恢复原来的颜色

2.你写错了，直接with open("dictionary.txt", "r") as f:会在当前工作路径找dictionary.txt，而不是在main.py的所在目录下寻找，建议换成with open(os.path.dirname(__file__)+"/dictionary.txt", "r") as f:，__file__是python内置的，返回本身python代码路径

**Comment by pythonbeginner14** [comment]
em，为什么"输入第0个5个字母的词语"

**Comment by QAQ0428** [comment]
感谢您的建议! 我已经改过来了

> em，为什么"输入第0个5个字母的词语"


> 1.必须要rich库，我认为如果只需要彩色地输出用控制字符\033[38;2;{red};{green};{blue}m就行了，里面写rgb值，之后\033[0m恢复原来的颜色
> 
> 2.你写错了，直接with open("dictionary.txt", "r") as f:会在当前工作路径找dictionary.txt，而不是在main.py的所在目录下寻找，建议换成with open(os.path.dirname(**file**)+"/dictionary.txt", "r") as f:，__file__是python内置的，返回本身python代码路径
